import type { Metadata } from 'next';
import './globals.css';
import { LibreBaskerville, MerriWeather, OpenSans } from '@/app/fonts';
import { Toaster } from 'sonner';
import ClientProviders from './ClientProviders';
import { cookies } from 'next/headers';
import { getCart } from '@/lib/shopify';
import Footer from '@/components/shared/Footer';
import SmoothScroll from '@/components/shared/SmoothScroll';
import HeaderServerWrapper from '@/components/shared/HeaderServerWrapper';
import { ViewTransitions } from 'next-view-transitions';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesList = await cookies();

  const cartId = cookiesList.get('cartId')?.value;
  const cart = getCart(cartId);

  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${LibreBaskerville.variable} ${OpenSans.variable} ${MerriWeather.variable}`}
      >
        <SmoothScroll>
          <body className="min-h-screen flex flex-col">
            <ClientProviders cart={cart}>
              <HeaderServerWrapper />
              <main className="grow">{children}</main>

              <Footer />
            </ClientProviders>
            <Toaster richColors />
          </body>
        </SmoothScroll>
      </html>
    </ViewTransitions>
  );
}
