import type { Metadata } from 'next';
import './globals.css';
import { Gotham } from '@/app/fonts';
import { Toaster } from 'sonner';
import ClientProviders from './ClientProviders';
import PageTransitionWrapper from '@/components/shared/PageTransitionWrapper';
import { cookies } from 'next/headers';
import { getCart } from '@/lib/shopify';
import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesList = await cookies();

  const cartId = cookiesList.get('cartId')?.value;
  const cart = getCart(cartId);

  return (
    <html lang="en" className={`${Gotham.variable}`}>
      <body className="min-h-screen flex flex-col font-gotham">
        <ClientProviders cart={cart}>
          <Header />

          <PageTransitionWrapper>
            <main className="grow container">{children}</main>
          </PageTransitionWrapper>

          <Footer />
        </ClientProviders>
        <Toaster richColors />
      </body>
    </html>
  );
}
